version: '3.4'

services:
  mongrove:
    image: mongrove
    build: .
    restart: always
    environment:
      - NODE_ENV=development
      - DISPLAY=host.docker.internal:0
      - WAIT_HOSTS=mongodb:27017
    expose:
      - 27017
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - data:/db/data

volumes:
  data:
